### ISSUE TITLE
Broken ChallengeQuest

### ISSUE THREAD

**Issue by Ryuzu** [Jetman823/Gunz1.5#10]
The CQ seems broken, i haven't tested previous commits. but this [one](https://github.com/Jetman823/Gunz1.5/commit/cb817a4d871c38cdaf9e50d6240bf8fa8b3f0469) 
Also i've changed the toolset to v141_xp
Added [mlog](https://dl.dropboxusercontent.com/s/jjq7t405sppc1jo/mlog.txt)
Here's the [callstack ](https://dl.dropboxusercontent.com/s/hceycuxn55eb64a/devenv_R7B2zrGQMQ.png)

**Comment by Jetman823** [comment]
Could be caused by my lightmap changes. I’ll look at it sometime this afternoon.

**Comment by Jetman823** [comment]
> 
> 
> The CQ seems broken, i haven't tested previous commits. but this [one](https://github.com/Jetman823/Gunz1.5/commit/cb817a4d871c38cdaf9e50d6240bf8fa8b3f0469) Also i've changed the toolset to v141_xp Added [mlog](https://dl.dropboxusercontent.com/s/jjq7t405sppc1jo/mlog.txt) Here's the [callstack ](https://dl.dropboxusercontent.com/s/hceycuxn55eb64a/devenv_R7B2zrGQMQ.png)

Fixed this with the latest commit.
